### ISSUE TITLE
Remove settings names/descriptions from database

### ISSUE THREAD

**Issue by rafalp** [rafalp/Misago#1065]
Currently, Misago uses database to store settings and setting groups. This looked like a great idea first, but eventually I've found this approach absolutely painful to maintain:

- changing translation strings requires DB migration
- changing settings order requires DB migration
- moving settings around requires DB migration
- changing settings inputs requires DB migration
- adding special data and validation to settings requires hacks
- its impossible to customize and add extra static fields to settings forms.

Ultimately, current settings implementation should be redone:

- Settings group model should be deleted
- Setting model should be simplified to contain only `setting`, `dry_value`, `default_value`, `python_type`, `is_public` and `is_lazy` fields.
- Setting groups should be a views, perhaps inheriting the generic `ChangeSettingsView`

### TODO

* [x] Replace generated settings forms with plain form views
* [x] Remove migration utils
* [x] Remove settings groups
* [x] Remove unused fields from settings models
* [x] Retroactively change settings migrations in other apps to noop
* [x] Create migration in `misago.conf` that creates all settings
