### ISSUE TITLE
Move admin user content deletion to celery task

### ISSUE THREAD

**Issue by rafalp** [rafalp/Misago#1213]
Currently Misago admin uses weird combination of JS API's refreshing page until all user's content has been deleted and such. Same may be the cause for deleting category together with its content.

Moving this action to celery task may make the thing more maintainable and reusable across the application.

### TODO

* [x] Reorganize user admin tests
* [x] Move user admin tests to pytest
* [x] Redo user with content deletion to use celery task
