### ISSUE TITLE
Move GraphQL API to ariadne-graphql-modules

### ISSUE THREAD

**Issue by rafalp** [rafalp/Misago#1378]
# Todo:

- [x] Auth
- [x] Avatars
- [x] Settings
- [x] Categories
- [x] RichText
- [x] Threads
- [x] Posts
- [x] Users
- [x] Search
- [x] Forum stats
- [x] Site setup

# Cleanups

- [x] Drop `_action` suffix
- [x] Gather mutations in `TypeMutations` collections
- [x] Format too long lines in `__schema__` strings
- [x] Update hooks reference
