### ISSUE TITLE
Users groups

### ISSUE THREAD

**Issue by rafalp** [rafalp/Misago#1384]
User should have one primary group.

User can have zero or more secondary group memberships.

Registered users are set as members of "default" group.

Users get permissions from user groups.

[Full draft](https://misago-project.org/t/simplifying-user-permissions/1097/)

# TODO

- [x] Group model
- [x] Default groups
- [x] Assign default group to user
- [x] Assign secondary groups to user
- [x] Update user's ACL key when their group memberships change

## GraphQL

- [x] Select
- [ ] Get members count
- [ ] Create
- [ ] Update
- [ ] Delete
- [ ] Reorder

**Comment by rafalp** [comment]
Closing this due to original plan for Misago 4.0 rewrite is cancelled. This work instead will be implemented on 0.x codebase in future.
