### ISSUE TITLE
QueryBuilder/Mapper Rewrite

### ISSUE THREAD

**Issue by rafalp** [rafalp/Misago#1387]
Our query builder/object mapper is quite messy and doesn't support joins, which is quite painful when working with m2m tables like user group memberships or moderators.

# Features

- [x] mapper
- [x] count
- [x] exists
- [x] select all
- [x] select all with column subset
- [x] select in batches
- [x] select in batches with column subset
- [x] select one
- [x] select one with column subset
- [x] filter
- [x] exclude
- [x] or filter
- [x] or exclude
- [x] filter/exclude with subquery
- [x] join
- [x] join missing relation
- [x] join over few relations (thread with first post's user)
- [x] join with selected columns (returning named tuples)
- [x] join with selected columns (returning tuple)
- [x] join count/exists
- [x] limit & offset
- [x] order by
- [x] delete
- [x] delete all
- [x] update
- [x] insert
- [x] bulk insert
- [x] distinct

# TODO

- [x] Add checks if join_name is defined
- [x] Cleanup select joins tests
- [x] Finish features
- [x] Split module into a package
- [x] Move existing implementations to new code
- [x] Delete old code
- [x] Write docs
