### ISSUE TITLE
Plugin system rewrite

### ISSUE THREAD

**Issue by rafalp** [rafalp/Misago#1524]
This is a rewrite of plugin system inspired largely by my experience from writing a new plugin system for abandoned v4 effort.

# Replace plugin list by plugin discovery in `plugins` directory

Instead of `plugins.txt` file that users will have to maintain, plugins could be discovered and loaded from dedicated `plugins` directory. This will simplify installation by users and logic for installing their dependencies on container's build time.

# Implement proper `action` and `filter` hook types for plugins to use

Misago should implement custom `action` and `filter` hooks:

- action hooks let plugins run extra code when an event happens in code.
- filter hooks let plugins run extra code around the standard logic implemented by Misago, and in rare cases, replace this logic altogether.

Reason for using custom action hooks instead of Django signals is to provide proper safety net in form of types.

# Write developer docs

Misago should have a developer documentation for new plugin system written as quickly as possible. The guide will be human-written, but the hooks reference will be generated from code, due to amount of work needed to maintain and otherwise keep it up to date.

# Roadmap

- [x] Replace plugin list with plugin directory
- [x] Install requirements
  - [x] Install `.[dev]` requirements by `plugins/plugin-dir/pyproject.toml` file
  - [x] Install requirements by `plugins/plugin-dir/requirements.txt` file
  - [x] Install requirements by `plugins/plugin-dir/requirements-dev.txt` file
- [x] Include plugins
  - [x] Include plugins in Python path
  - [x] Include plugins in `INSTALLED_APPS`
  - [x] Include plugins urls in `urlpatterns`
- [x] Display plugins list in admin
  - [x] Gather manifests from `plugin/misago_plugin.py` files
- [x] Install plugins from pip using `pip-install.txt` file
  - [x] Include plugins in `INSTALLED_APPS`
  - [x] Display plugins on plugins list in admin
- [x] Add `plugin_data` json field to some models, set GIN index on it
  - [x] Implement `PluginDataModel` abstract model
- [x] Implement hooks
  - [x] Filter hook type
  - [x] Action hook type
  - [x] Template plugin outlet tag
  - [x] Template outlet has plugins conditional tag
- [x] Docs
  - [x] Plugin structure
  - [x] Plugin installation (local)
  - [x] Plugin installation (pip)
  - [x] Plugin tutorial
  - [x] Plugin manifest
  - [x] Plugin hooks
  - [x] Plugin data
  - [x] Template outlets
  - [x] Template overrides
  - [x] Plugin urls
  - [x] List of links to other extension points in Misago (link to custom notifications)
