### ISSUE TITLE
Create basic posting and thread pages

### ISSUE THREAD

**Issue by rafalp** [rafalp/Misago#1774]
It took me 40 days to do new threads lists, and those are still not completely finished. If I am going to follow this approach to posting and thread views, its going to take me another 80 days.

Instead I would like to use an alternative approach to those and first implement very basic versions for them, and then improve them in multiple small iterations. That way I could have many small PRs instead of two gigantozauric PRs.

# TODO

- [x] Start new thread
- [x] Read thread contents
- [x] Reply to a thread
- [x] Edit a reply in a thread

**Comment by rafalp** [comment]
I've instead merged minimal thread posting view first. Now I'll do minimal thread views. Those minimal thread views will check user permission to see a thread and will display to them a thread with paginated posts list. Reply/edit/moderation/etc will happen as separate extra PRs.

**Comment by rafalp** [comment]
I will keep this open until minimal thread view lets users post new replies and edit existing ones.

**Comment by rafalp** [comment]
I'll keep this open until all todo's are finished.

**Comment by rafalp** [comment]
Closing this as done, seeing how basic start/reply/edit flow is all implemented and recent changes are only extending them with new features, which means the goal of having basic posting views has been achieved.
