### ISSUE TITLE
Framework Checklist

### ISSUE THREAD

**Issue by rafalp** [rafalp/Misago#297]
- [x] All issues closed or reassigned
- [x] All tests pass
- [x] Public APi's are documented
- [x] Flake8 and landscape raises no real issues
