### ISSUE TITLE
User Auth Checklist

### ISSUE THREAD

**Issue by rafalp** [rafalp/Misago#362]
- [x] Fixtures
- [x] Make sure members always have member role and guests always have guest role
- [x] Bans
- [x] Online tracker
- [x] Captcha
- [x] Register
- [x] Activate
- [x] Reset password
- [x] Sign in
- [x] Change credentials in UserCP
- [x] Django admin support
