### ISSUE TITLE
Threads checklist

### ISSUE THREAD

**Issue by rafalp** [rafalp/Misago#410]
**Todo for 0.6**

* [x] Events
* [x] Forum threads list
* [x] Goto views
* [x] In-thread moderated posts list
* [x] In-thread reported posts list
* [x] Moderated threads list
* [x] New threads list
* [ ] Post changelog and diff
* [ ] Posts moderation
* [x] Reads tracker
* [ ] Subscriptions
* [ ] Thread view
* [x] Threads moderation
* [x] Unread threads list
* [ ] User profile tabs (waits for threads views)

**Comment by rafalp** [comment]
Superseded by #543
