### ISSUE TITLE
Add python social auth support

### ISSUE THREAD

**Issue by rafalp** [rafalp/Misago#416]
This was scratched on forums already:

http://misago-project.org/thread/how-do-i-get-started-on-creating-an-extension-for-misago-309/

I've had professional experience with sign on via [social-auth](https://github.com/python-social-auth), so its likely that I'll go with that in one of future releases.

### TODO:

- [x] Expose list of supported providers to the UI
- [x] Display buttons on Login form
- [x] Display buttons on Registration form
- [x] Return `None` if misago's default authentication backend receives no username or password
- [x] Handle social-auth errors
- [x] Sign in to existing account if email exists and user is not banned
- [x] Don't sign in to existing account that needs e-mial or user activation
- [x] Try to pick username for newly created user if possible
- [x] Try to create new user if valid email and username were received from the API (add tests)
- [x] Interrupt with registration form if no new email is given or there is a problem with user details
- [x] Don't sign in to newly created account if we are requiring admin-activation for accounts
- [x] Send greeting e-mail if new account has been created with social sign-in.
- [x] Handle useless user password in their control panel
- [x] Display information about useless user password in admin
- [x] Update project template
- [x] Periodically clean `social_auth_partial` table in Database
- [ ] Write social auth setup guide in docs
