### ISSUE TITLE
Making content hierarchy flat

### ISSUE THREAD

**Issue by rafalp** [rafalp/Misago#481]
See following thread for details:

http://misago-project.org/thread/making-misago-flat-board-392/#post-1204

**Todo**
* [x] **Drop regular forum roles**
* [x] **Rename forums to categories**
* [ ] ~~Limit category depth to 2 levels~~
* [x] **All threads view**
* [x] **Display subcategory threads in category**
* [x] **Add root-level announcements**

**Comment by rafalp** [comment]
Already done on master
