### ISSUE TITLE
Get rid of "from misago.conf.defaults import *"

### ISSUE THREAD

**Issue by rafalp** [rafalp/Misago#590]
After this change the `misago.conf.defaults` module becomes source of fallback configuration for Misago, resolved via mechanism like below:

```
try:
    getattr(django.conf, setting)
except AttributeError:
    getattr(misago.conf.defaults, setting)
```

**TODO**

* [x] update `settings.py` template to use current for Django 1.10
* [x] add misago apps to `INSTALLED_APPS`
* [x] add misago middlewares to `MIDDLEWARE`
* [x] add misago context processors to `TEMPLATES.OPTIONS.context_processors`
* [x] move required Django configuration from `misago.conf.defaults`
* [x] move required Rest Framework configuration from `misago.conf.defaults`
* [x] move required Debug Toolbar configuration from `misago.conf.defaults`
* [x] include email settings in project template's settings
* [x] remove non-misago settings from `misago.conf.defaults`
* [x] update `misago.conf.settings` to fallback to `misago.conf.defaults` if `django.conf.settings` fails to define requested setting.

**Comment by rafalp** [comment]
Actually, let's shove this into Alpha 1.
