### ISSUE TITLE
Replace pickled fields with json fields

### ISSUE THREAD

**Issue by rafalp** [rafalp/Misago#593]
Here and there Misago uses pickled dicts to store data in DB. Django 1.10 supports JSON field which means at least some of those fields can be replaced with safer JSON field instead of pickled python bytecode that's executed on unpickle

**TODO**

* [x] remove serialization from conf
* [x] remove serialization from roles
* [x] remove secret_key_changed feature
