### ISSUE TITLE
Tool for 0.5->0.6 migrations

### ISSUE THREAD

**Issue by rafalp** [rafalp/Misago#600]
**TODO**

* [x] Settings
* [x] Users
* [x] Avatars
* [x] Follows
* [x] Blocks
* [x] Names history
* [x] Bans
* [x] Categories
* [x] Thread labels
* [x] Threads
* [x] Posts
* [x] Mentions
* [x] Edits
* [x] Convert upvotes to likes
* [x] Attachments
* [x] Polls
* [x] Private threads participants
* [x] Prune threads without participants

**Redirects**

* [x] Make selects on MovedId model faster, use index on model and old_id field, change model to int
* [x] 301 redirects from old urls to new ones

**MARKUP CHANGES**

* [x] Replace old quotes with newstyle `[quote][/quote]`
* [x] Replace emojis with their text
* [x] Update attachments urls

**Things that won't be migrated**

* User ranks - all users are moved to default rank
* Permissions - have to be set manually after migration
* Events - nice to have (they add to thread's story), but proper implementation of migration algorithm would be task that I'm unwilling to invest time into

**Comment by ioanb7** [comment]
Hi,

Beautiful project, all my respect for the work done.

When do you think 0.6 version is going to be released and do you think it's almost a good idea to install 0.6 instead of 0.5 - despite of the warning?

Otherwise, is this tool going to migrate from 0.5 to 0.6 all right?

Regards,
Ioan.

**Comment by rafalp** [comment]
Hey,

*Almost* makes check of difference, like "almost catched the flight" ;) The warning is here for a good reason - I am not bothering with nice migrations until 0.6 releases, so if you setup site on 0.6 now, you'll be unable to update database without plenty of work on your side.

But yep, the tool will move the data form 0.5 to 0.6 once it hits.

**Comment by rafalp** [comment]
DB for 0.6 is complete, I can now get to work on data migrator for folk running 0.5 to be able to move over to 0.6

**Comment by rafalp** [comment]
Datamover is now moving users without an issue. I'll try get rest of stuff over weekend, but there's change I'll run into compatibility issues in posts markup etc. that will slow me down.

**Comment by ioanb7** [comment]
Thank you Rafal!

**Comment by rafalp** [comment]
And just fix posts contests on move and this is done.
