### ISSUE TITLE
Avatar storage needs to support clustered deployments

### ISSUE THREAD

**Issue by rafalp** [rafalp/Misago#610]
Currently avatar storage is hardcoded to filesystem, meaning it'll won't work in situation when community is hosted across few machines.

Possible solution would be creating "Avatar" model related with user, and avatar cache json field on user model, to save up on need to fetch avatar url's from related models.

Upside of new implementation would ability to drop both `avatar_hash` and `avatar_server`.

**TODO**

* [x] Move users avatars to Avatar model
* [x] Move gallery avatars to GalleryAvatar model
* [x] Provide setting for blank/guest avatar, `MISAGO_GUEST_AVATAR`
* [x] Remove avatars server
