### ISSUE TITLE
Move constants to either `constants.py` or owning classes

### ISSUE THREAD

**Issue by rafalp** [rafalp/Misago#648]
**TODO**

* [x] Move constants in `misago.users.models.user` under the User model
* [x] Drop `AUTO` prefix fro from `AUTO_SUBSCRIBE_` constants
* [x] Rename `AUTO_SUBSCRIBE_NOTIFY_AND_EMAIL` to `AUTO_SUBSCRIBE_ALL`
* [x] Change `ACTIVATION_REQUIRED_` to `ACTIVATION_`
* [x] Change `LIMITS_PRIVATE_THREAD_INVITES_TO_` to `LIMIT_INVITES_TO_`
* [x] Ban
* [x] Remove `BAN_` prefix from Ban model's constants
* [x] Change `BANS_CHOICES` to `CHOICES`
* [x] Category
* [x] Move `cachebuster_register_cache` names to `constants.py`
