### ISSUE TITLE
Localise migrated data

### ISSUE THREAD

**Issue by rafalp** [rafalp/Misago#653]
This superseds #583.

Following items should be saved to DB in english, and localised upon render

**TODO**

* [x] Settings are localised
* [x] Ranks are localised *(may be tricky due to slugs)*
* [x] Roles are localised *(admin only)*
* [x] Category roles are localised *(admin only)*

**Comment by rafalp** [comment]
Belaying this issue for next release
