### ISSUE TITLE
Release 0.6 alpha 1 on PYPI

### ISSUE THREAD

**Issue by rafalp** [rafalp/Misago#668]
**todo**

* [x] do few dev releases to test if package is setup correctly
* [x] remove prelease warning bar from templates
* [x] bump version to 0.6.0a1 in source code
* [x] publish
