### ISSUE TITLE
Write management task for clearing expired readtracker entries

### ISSUE THREAD

**Issue by rafalp** [rafalp/Misago#674]
@luis-wang

I would like you to create django admin task that would be deleting entries ([CategoryRead and ThreadRead](https://github.com/rafalp/Misago/blob/master/misago/readtracker/models.py)) from readtracker that have `last_read_on` older than specified by [MISAGO_READTRACKER_CUTOFF](https://misago.readthedocs.io/en/latest/developers/settings.html#misago-readtracker-cutoff) setting.

This task should be added to example `cron.txt` that's in `project_template` directory. It should also provide tests ensuring that only items older than cutoff date are deleted.

If you have any questions, feel free to ask.

**todo**

* [x] Write management command
* [x] Write tests
* [x] Add to cron task
* [x] Mention in relase notes

**Comment by luis-wang** [comment]
ok, I will do it ,  thank you !
