### ISSUE TITLE
Make readtracker post-accurate instead of thread-accurate.

### ISSUE THREAD

**Issue by rafalp** [rafalp/Misago#675]
Post-accurate read tracker will allow Misago to greatly improve thread read states accuracy and account for following actions that are not handled currently:

- posts edits
- unapproved posts

The downside is thread read resolution will become costlier, especially on active forums. And there's question of performance of "unread threads" list.

This is worth researching for future release.

**Questions that need answers**

* How costful would it be to resolve if threads list items are read?
* How costful would it be to resolve if category is read?
* How costful would it be to resolve if user should get notification about new reply?
* If post edits should mark thread as unread, how will this system defend itself from frequent typos by posts authors?

**TODO**

* [x] Create `PostRead` model
* [x] Migrate users readstates to `PostRead` model
* [x] Remove "mark as read" action
* [x] Update signals to sync `PostRead`
* [x] Simplify cutoff dates implementation to rely on user's join date or `timezone.now() - MISAGO_READTRACKER_CUTOFF`
* [x] Create `posttracker`
* [x] Refactor `categoriestracker` and `threadstracker`
* [x] Update views
* [x] Remove `ThreadRead` model
* [x] Remove `CategoryRead` model
* [x] Update management command trimming readtracker to use `PostRead`
* [x] Update UI to don't mark all previous posts as read when single post is read
* [x] Update UI to sync thread read state on post read

**Comment by rafalp** [comment]
Unpinning from alpha for now, I would like to eventually get this into Misago's codebase, but I'm feeling It's best to get it sometime after html and css is wrapped up.
