### ISSUE TITLE
Use YAPF to auto-format code.

### ISSUE THREAD

**Issue by rafalp** [rafalp/Misago#702]
Setting this as reminder for myself: I would like to eventually automate code formatting process for Misago with some tool like YAPF.

**TODO**

* [x] exclude `misago.conf.defaults`
* [x]  add separator before closing bracket so args and lists don't use "compact" formattings
* [x] cleanup comments
* [x] add after-yapf cleanup step for complex dicts

**Comment by rafalp** [comment]
Assigning this for alpha 3 now. I'm pretty pleased with how YAPF formats misago's codebase already, and it seems there are even better things in the pipeline for next release.

I've also made branch for just messing around with yapf for everyone interested to have look at Misago's yapified codebase:

https://github.com/rafalp/Misago/tree/yapf/misago
