### ISSUE TITLE
Make posts list component responsive

### ISSUE THREAD

**Issue by rafalp** [rafalp/Misago#750]
This is biggie because threadview is one of key parts of site, and yet its not responsive currently.

**TODO**
* [x] threadview posts headers
* [x] threadview posts footers
* [x] threadview events
* [x] user profile posts lists
* [ ] search results posts lists
