### ISSUE TITLE
Make threads list tabular instead of redditish

### ISSUE THREAD

**Issue by rafalp** [rafalp/Misago#764]
**Todo**

* [x] Redesign threads list react.js component
* [x] Don't display current category on threads list
* [x] Busy state
* [x] UI preview
* [x] Html template
* [x] Remove top-category resolution and time performance gains
* [x] Fix build
