### ISSUE TITLE
User profile fields

### ISSUE THREAD

**Issue by rafalp** [rafalp/Misago#865]
One of needs that internet forum has to meet is way a for its administrators to extend the user profiles with additional fields, be it contact options, bio's, their pc setup's, favorite character class, gender, etc. ect.

Currently doing so requires one to get dirty with the code, de facto forking Misago's codebase to achieve what one's after.

Speaking from the personal experience, the goto way of doing custom profile fields in Internet forums is via admin control panel and it's "custom profile fields"... but thats because its business as usual in the PHP software to be as configurable as possible with the admin panel for folk using those.

With Misago I would like to follow the path set by Django, and allow people to create custom profile fields as classes inheriting base `ProfileField` type, registered in the `MISAGO_PROFILE_FIELDS` settings that would mimic django admin's fieldsets setting like such:

```
MISAGO_PROFILE_FIELDS = [
    {
        'name': _("Personal"),
        'fields': [
            'misago.users.profilefields.name',
            'misago.users.profilefields.bio',
            'misago.users.profilefields.location',
        ],
    },
    {
        'name': _("Contact"),
        'fields': [
            'misago.users.profilefields.email',
            'misago.users.profilefields.www',
            'misago.users.profilefields.twitter',
            'misago.users.profilefields.fb',
        ],
    },
]
```

**TODO**

* [x] Add `profile_fields` hstore field on user model
* [x] Create profile extensions module that loads fields
* [x] Add admin form for profile fields
* [x] Search profile extensions in admin
* [x] Add "Edit details" on user options page
* [x] Add "Details" on user profile
    * [x] Edit fields by user on his details tab
    * [x] Edit fields of other user as moderator
* [x] Support some basic fields
    * [x] Bio (text block)
    * [x] Full name
    * [x] Gender (select field)
    * [x] Location
    * [x] Skype
    * [x] Twitter (extra cleaning/normalization)
    * [x] Website (url)
* [x] Display additional metadata for users (readonly fields)
    * [x] Join IP
    * [x] Last IP
* [x] Stub `MISAGO_PROFILE_FIELDS` setting in project template
* [x] Write management command that lists existing keys in users `extra`s
* [x] Write management command that deletes given key from users `extra` property
* [x] Add logger for profile fields change
* [x] Write documentation

**Comment by rafalp** [comment]
Reopening as I still have little meddling to do with the logger before I'll be closing this up.
