### ISSUE TITLE
Threads and posts permissions handling of closed category/thread state differs

### ISSUE THREAD

**Issue by rafalp** [rafalp/Misago#887]
Some actions permissions test to act in closed category/thread (via can_close_threads perm) always, while some only in the "non-mod user is editing owned content".

I would like to unify this across the board to require that to act in closed category/thread, one has to have `can_close_threads` permission first.

Perms check order should go as follows:

* test authentication
* test permission
* owner-specific tests
* test closed category/thread

**TODO**

* [x] Write thread allow change weight tests
* [x] Write thread allow hide test
* [x] Write thread allow unhide test
* [x] Write thread allow move test
* [x] Write thread allow merge test
* [x] Write thread allow approve test
* [x] Reorder checks in posts permissions tests
* [x] Add closed/open checks in events permissions tests
* [x] Test closed/open in posts split
* [x] Test closed/open in posts move
* [x] Test closed/open in posts merge
* [x] Add closed/open checks to revert button in post edits history
* [x] Add closed/open checks in attachments permissions tests
* [x] Add closed/open checks in polls permissions tests
