### ISSUE TITLE
Enchance input validation in API methods

### ISSUE THREAD

**Issue by rafalp** [rafalp/Misago#893]
Currently majority of Misago's API's merrily assume the best case scenario when working with user inputs. This means some endpoints assume that `request.data` is an list while other endpoints assume its an dict.

This means Misago will not always communicate invalid request structures via proper error, instead elevating to 500 as it fails to spot that data is of invalid type or structure.

This could be improved via writing serializers for initial validation of incoming data, like such:

```python
from rest_framework import serializers

class BulkPatchSerializer(serializers.Serializer):
    ids = serializers.ListField(
        child=serializers.IntegerField(min_value=0),
        max_length=40,
        min_length=1,
    )
    ops = serializers.ListField(
        child=serializers.DictField(),
        min_length=1,
        max_length=10,
    )
```

**TODO**

* [x] Markup API assumes that `request.data` is `dict`
* [x] Vote in poll assumes that `request.data` is `list` - incorrectly sending json map passes silently
* [x] Merge posts endpoint
* [x] Move posts endpoint
* [x] Posts split endpoint in `clean_posts_for_split`
* [x] Delete posts
* [x] Merge thread
* [x] Merge threads
* [x] Delete threads
* [x] Login API
* [x] Resend activation
* [x] Reset password
* [x] Change forgotten password
* [x] Register API
* [x] Change user avatar API
* [x] Posting endpoints need tests for incorrect inputs

**Comment by rafalp** [comment]
Small sidestep: find out under which conditions ListField errors on `required`
