### ISSUE TITLE
SPA Checklist

### ISSUE THREAD

**Issue by rafalp** [rafalp/Misago#933]
**TODO**

* [ ] Framework
  * [ ] Ajax
  * [ ] Form
  * [ ] Route boilerplate (loading/error)
  * [ ] Modal
  * [ ] Snackbar
  * [ ] Validation
  * [ ] Ticks
* [ ] Auth
  * [ ] Register
  * [ ] Login
  * [ ] Activate
  * [ ] Resend activation
  * [ ] Resend password reset
  * [ ] Reset forgotten password
  * [ ] Polling
* [ ] Categories list
* [ ] Threads
  * [ ] Listing
  * [ ] Detail
  * [ ] Moderation
  * [ ] Goto
  * [ ] Posting
* [ ] Private threads
  * [ ] Listing
  * [ ] Detail
  * [ ] Moderation
  * [ ] Goto
  * [ ] Posting
* [ ] User options
  * [ ] Get options views
  * [ ] Change options
  * [ ] Change avatar
* [ ] Users
  * [ ] Users lists
  * [ ] User profile
  * [ ] User posts
  * [ ] User threads
  * [ ] User follows
  * [ ] User followers
  * [ ] User profile fields
* [ ] Search
  * [ ] Quick search
  * [ ] Full search
* [ ] Legal
  * [ ] Terms of service page/api
  * [ ] Privacy policy page/api
