### ISSUE TITLE
API error responses cleanup

### ISSUE THREAD

**Issue by rafalp** [rafalp/Misago#934]
`400` - should ALWAYS contain dict of lists of errors (as in. `serializer.errors`) or, if action sent was bulk, list of dicts following the `{id, code[, detail]}` structure. Misago may break this contract if error 400 comes from malformed data.
`403` - should ALWAYS contain dict with `detail` key containing either plaintext message (not array!), or structure with `html` and `plaintext` keys. May include additional keys like `extra` or `expires_on`.
`404` - should always contain dict with `detail` key containing plaintext message. In case this message is `NOT FOUND`, it will be replaced by UI with one that makes sense in context.

**TODO**

* [x] Change `ApiPatch.dispatch()` behavior.
* [x] Change `ApiPatch.bulk_dispatch()` behavior.
* [x] Revamp patch actions to don't coerce all errors to `PermissionError` or`Http404`.
* [x] Change API endpoints error handling.
* [x] Change  API's exception handler handling to follow contract for 404 errors.
