### ISSUE TITLE
Degray theme, add more colors or variety

### ISSUE THREAD

**Issue by rafalp** [rafalp/Misago#951]
Misago's current theme is grays galore, with little purple here and there for accents.

I've used to be way faaaar on the side of "white backgrounds burn eyes out!" camp, but I have found the light, and would like to experiment some with Misago's design in next release.

**TODO**

* [x] Desktop navbar
* [x] Mobile navbar
* [x] Desktop guest menu
* [x] Mobile guest menu
* [x] Desktop user menu
* [x] Mobile user menu
* [x] Navbar search
* [x] Desktop header
* [x] Mobile header
* [x] Error pages
